try:
    doSomething
except Exception as e:         
    print(e)

