try  
{  
    int i = 1;
}  
catch (Exception ex)
{  
    Console.WriteLine(ex.Message);
}  

